### ISSUE TITLE
Urlparse module missing

### ISSUE THREAD

**Issue by zabzal** [PredixDev/predixpy#10]
First off, thanks for putting together what seems to be a good Python client for Predix. My day to day use of Python involves Python 3.4 +. I know your roadmap for this project has Python 3 compatibility. One of the first issues I came around while trying to use the library with Python 3 is that Urlparse was missing. The code I tried running was:

`import predix.admin.app`

So far I found that the `urlparse` module has been rename to `urllib.parse` in python 3. Not sure how soon Python 3 compatibility will be available. Do let the wider community know what we can do to help.

Wonderful work so far.

**Comment by j12y** [comment]
This is good feedback, thanks @zabzal.  Intention was to have it ready before launch but ran out of time, but should be very soon because several projects are in Python 3.x already that will benefit from having this supported in both environments.

**Comment by zabzal** [comment]
@j12y Looking forward to the Python 3.x version.

**Comment by j12y** [comment]
Should be available with `pip install predix==1.0.0rc1` which will be the next release.
