### ISSUE TITLE
_get_websocket sometime fails

### ISSUE THREAD

**Issue by kbischop** [PredixDev/predixpy#11]
Hi,

i´m using predixpy for my application. Great work. 

I found one small problem.

In my python application I´m using freeopcua client to connect to an opc ua server. I subscribe to some variable. Whenever a variable value changes I push the new value to the prefix time series.

In my application it can happen that the opc ua variable does not change very often, only one time every two hours. The first time I send data to the timeseries, _get_websocket creates a new web socket connection (if not self.ws...), the second time I send data to the time series, _get_websocket uses the existing self.ws. This normally works, but if the websocket connection gets broken in the meantime (for whatever reason), _get_websocket does not detect that and always returns the existing and now broken self.ws . _get_websocket should detect if self.ws is broken and then create a new one. I fixed this with a try..except hack, but it´s not a nice solution. Maybe there is an elegant way to detect if the web socket is still in a working state.

**Comment by j12y** [comment]
I noticed this last week myself when doing some testing on long-lived connections.  

I will try to more elegantly detect the websocket connection times out and re-establish.  The try/except seems like a pretty good interim workaround.

Thanks for reporting -- will try to get a new version out very soon.

**Comment by turnerth** [comment]
FWIW, the way we implemented the java predix-websocket-client is with a connection pool.  When the connection object is needed and retrieved from the pool, we check the connection status.  If it fails we throw the connection away and create a new one for the pool.  Once the pool determines it's a good connection we return it to the calling party.
