### ISSUE TITLE
GET Asset Collection uri varibale has extra string i.e 'v1'

### ISSUE THREAD

**Issue by mfaizanmajeed** [PredixDev/predixpy#21]
wrong "uri = self.uri + '/v1' + collection"
should be like "uri = self.uri + '/' + collection"
in
get_collection(self, collection, filter=None, fields=None, page_size=None)
& also in put & post

**Comment by j12y** [comment]
Thanks for sending this in.  According to the docs there is supposed to be a `/v1/` in the URL.
https://www.predix.io/services/service.html?id=1171#!/User_Defined_Domain_Objects

If you don't mind clarifying, did you use PredixPy to configure the URI in your manifest.yml or are you specifying the uri yourself?  Do you know which API endpoint you are using?

I'm just double-checking nothing else changed and integration tests are looking for this possibility.  Thanks again for your help.

**Comment by mfaizanmajeed** [comment]
1-Yes, I used PredixPy to configure URIs in manifest.yml. 
2-https://predix-asset.run.aws-usw02-pr.ice.predix.io/<custom-asset-type>/<ID>
from https://predix-toolkit.run.aws-usw02-pr.ice.predix.io/#!/asset

I think /v1/ is in timeseries query or ingestion according to predix tool kit "https://predix-toolkit.run.aws-usw02-pr.ice.predix.io/#!/tsQuery",  i.e "https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/tags".

**Comment by mfaizanmajeed** [comment]
Yes you are right according to documentation there is /v1/ , don't know may be both are ok

**Comment by j12y** [comment]
I think we're ok here on this, but let me know if not the case or you saw any other issues.

Latest release available with `pip install predix==1.0.0rc1`, but always room to improve.
